# Generated by Django 4.1.4 on 2022-12-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webanalytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snippet", old_name="language", new_name="roomid",
        ),
        migrations.RemoveField(model_name="snippet", name="code",),
        migrations.RemoveField(model_name="snippet", name="linenos",),
        migrations.RemoveField(model_name="snippet", name="style",),
        migrations.RemoveField(model_name="snippet", name="title",),
    ]
