# Generated by Django 4.1.4 on 2022-12-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webanalytics", "0003_alter_snippet_roomid"),
    ]

    operations = [
        migrations.RenameModel(old_name="Snippet", new_name="Booking",),
    ]
